### ISSUE TITLE
webserver 端口号偏小就会报错

### ISSUE THREAD

**Issue by rachardking** [ecomfe/edp#316]
知道是什么原因吗

**Comment by otakustay** [comment]
你小到啥程度了，报啥错？

**Comment by rachardking** [comment]
禁用了sudo吗？

**Comment by rachardking** [comment]
启用80端口 mac下 用sudo
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at module.exports (/usr/local/lib/node_modules/edp-webserver/lib/start.js:54:41)
    at Object.cli.main (/usr/local/lib/node_modules/edp-webserver/cli/webserver/start.js:123:9)
    at done (/usr/local/lib/node_modules/edp/lib/cli.js:123:35)
    at Object.exports.parse (/usr/local/lib/node_modules/edp/lib/cli.js:156:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/edp/bin/edp-cli:4:5)
    at Module._compile (module.js:456:26)

**Comment by errorrik** [comment]
@leeight 在edp的cli里面，leaveRootMode了。为啥这么干捏？

**Comment by leeight** [comment]
因为担心代码出错，发生不可预知的问题，就把权限降下来了
