### ISSUE TITLE
webserver最新版运行报错

### ISSUE THREAD

**Issue by otakustay** [ecomfe/edp#328]
```sh
~/Dev/ssp/ssp(branch:es6-test) » edp webserver start .                                                                           otakustay@Gray-MacBook-Pro-2
module.js:338
    throw err;
          ^
Error: Cannot find module 'connect-logger'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/usr/local/lib/node_modules/edp-webserver/lib/middleware/logger.js:13:12)
    at Object.exports.attachTo (/usr/local/lib/node_modules/edp-webserver/lib/middleware/defaults.js:24:13)
    at module.exports (/usr/local/lib/node_modules/edp-webserver/lib/start.js:45:14)
    at Object.cli.main (/usr/local/lib/node_modules/edp-webserver/cli/webserver.js:123:9)
    at done (/usr/local/lib/node_modules/edp/lib/cli.js:123:35)
    at Object.exports.parse (/usr/local/lib/node_modules/edp/lib/cli.js:156:9)
```

@leeight

**Comment by leeight** [comment]
试试最新的 npm i edp-webserver@beta 看看

**Comment by otakustay** [comment]
OK了
