### ISSUE TITLE
外部用户怎样发布私有包

### ISSUE THREAD

**Issue by Phinome** [ecomfe/edp#335]
R;T
非baidu用户，在项目中使用 edp 作为整个构建工具，此时项目中需要用到自身的一些代码库，此时，已按照 edp 的AMD规范和包管理规范处理完毕，请问接下来该如何发布私有包？
谢谢～
@leeight @errorrik

**Comment by leeight** [comment]
可以考虑 edp import http://xxxxx.tar.gz ？

**Comment by Phinome** [comment]
现在支持？

**Comment by otakustay** [comment]
支持，就是有几个限制：

1. 必须是`.tar.gz`的，用`.zip`的不行
2. 因为不知道包名了，所以update无效，要update的话你得删掉dep下那个目录再做一次import

@leeight edp对registry的要求是遵循npm对吧？我在做下一版本package的时候考虑下私有registry

**Comment by Phinome** [comment]
多谢灰大和 leeight 。正在 import 中

**Comment by Phinome** [comment]
看了一下 `edp-package/lib/import-from-file.js` 的代码：
```javascript
switch (fileExtname) {
        case 'gz':
        case 'tgz':
            extractMethod = extract.tgz;
            break;
        case 'zip':
            extractMethod = extract.zip;
            break;
        default:
            throw new Error(fileExtname + ' file is not supported!');
    }
```

貌似是支持 zip 的

**Comment by Phinome** [comment]
edp import xxx.tar.gz :
```javascript

/usr/local/lib/node_modules/edp-package/lib/import-from-file.js:86
        var dstname = context.getPackageDstName(packageInfo.name);
                                                           ^
TypeError: Cannot read property 'name' of null
    at /usr/local/lib/node_modules/edp-package/lib/import-from-file.js:86:60
    at fn (/usr/local/lib/node_modules/edp-package/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/edp-package/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

```

**Comment by leeight** [comment]
`xxx.tar.gz`里面有package.json么，执行`tar tzvf xxx.tar.gz`把输出发过来看看

**Comment by Phinome** [comment]
```
lodash
├── 3.10.1
│   ├── LICENSE
│   ├── README.md
│   ├── package.json
│   └── src
│       └── lodash.js
└── 3.10.1.md5

```

package.json

```javascript
{
  "name": "lodash",
  "version": "3.10.1",
  "main": "lodash.js",
  "private": true,
  "devDependencies": {
    "curl-amd": "0.8.12",
    "dojo": "~1.10.0",
    "jquery": "~1.11.0",
    "platform": "~1.3.0",
    "qunit-extras": "~1.4.0",
    "qunitjs": "~1.18.0",
    "requirejs": "~2.1.0"
  },
  "scripts": { "test": "node test/test" },
  "volo": {
    "type": "directory",
    "ignore": [
      ".*",
      "*.custom.*",
      "*.log",
      "*.map",
      "*.md",
      "bower.json",
      "component.json",
      "doc",
      "node_modules",
      "perf",
      "test",
      "vendor"
    ]
  }
}


```

**Comment by leeight** [comment]
你应该把 `3.10.1` 弄一个 `*.tar.gz` 出来的吧？

**Comment by leeight** [comment]
我怀疑 lodash 的代码如果不处理的话，可能无法正确 build 呢

**Comment by Phinome** [comment]
`lodash` 的代码和 `underscope` 的代码几乎一致，关键是都 `AMD` 了。
我试试把 `3.10.1` 这个文件夹弄个 `*.tar.gz`

**Comment by leeight** [comment]
实际上`lodash`和`underscope`，以及很多开源的代码都是`UMD`，我们发布到`edp-registry`上面的开源代码，有些是需要经过修改的，比如改成了`define(function(require){`的形式，从而可以顺利通过`edp-build`的编译。

**Comment by Phinome** [comment]
我特意使用的 `lodash` `AMD` 的版本。

lodash.js 

```javascript
// Some AMD build optimizers like r.js check for condition patterns like the following:
  if (typeof define == 'function' && typeof define.amd == 'object' && define.amd) {
    // Expose lodash to the global object when an AMD loader is present to avoid
    // errors in cases where lodash is loaded by a script tag and not intended
    // as an AMD module. See http://requirejs.org/docs/errors.html#mismatch for
    // more details.
    root._ = _;

    // Define as an anonymous module so, through path mapping, it can be
    // referenced as the "underscore" module.
    define(function() {
      return _;
    });
  }
  // Check for `exports` after `define` in case a build optimizer adds an `exports` object.
  else if (freeExports && freeModule) {
    // Export for Node.js or RingoJS.
    if (moduleExports) {
      (freeModule.exports = _)._ = _;
    }
    // Export for Rhino with CommonJS support.
    else {
      freeExports._ = _;
    }
  }
  else {
    // Export for a browser or Rhino.
    root._ = _;
  }

```

**Comment by Phinome** [comment]
多谢 @leeight 提供 `underscore.1.8.5.tgz` 包。参考了这个包，问题已经解决了。
总结一下就是：

1. `tgz` , `zip` 都是可以导入的。
2. 需要导入的 `js` 必须是支持 `AMD` 的。即：
```javascript
if (typeof define == 'function' && typeof define.amd == 'object' && define.amd) {
    // Expose lodash to the global object when an AMD loader is present to avoid
    // errors in cases where lodash is loaded by a script tag and not intended
    // as an AMD module. See http://requirejs.org/docs/errors.html#mismatch for
    // more details.
    root._ = _;

    // Define as an anonymous module so, through path mapping, it can be
    // referenced as the "underscore" module.
    define(function() {
      return _;
    });
  }
```
3. 包结构需要是这样：
```
package
│   ├── LICENSE
│   ├── README.md
│   ├── package.json
│   └── src
│       └── lodash.js
```

其中的， 目录名必须是 `package` ，`package.json` 必须为一个符合 `npm package` 规范的 `JSON`。

大致就这样了，若有啥不对的地方，还请 @leeight 指正。

**Comment by leeight** [comment]
你把 `loadsh` 的代码改改吧。最后那部分 `UMD` 相关的代码去掉，直接 `return _`即可。最外层改成 `define(function(require)`

**Comment by otakustay** [comment]
umd不应该有问题 我们自己的eoo和Promise都是umd的啊

**Comment by Phinome** [comment]
嗯，那个无关紧要吧？引入 `esl ` 后，不会进入 `else` 那个判断了吧。

**Comment by leeight** [comment]
因为`edp-build`并没有单独针对UMD的处理逻辑，如果能用，只能说是恰好能用，并不保证所有情况下都会没问题。

**Comment by Phinome** [comment]
明白了，我改改。
